name             'evanstack'
maintainer       'Evan Ochs'
maintainer_email 'evan.ochs@rackspace.com'
license          'All rights reserved'
description      'Installs/Configures evanstack'
long_description 'Installs/Configures evanstack'
version          '0.1.0'

#depends 'phpstack'
#depends 'platformstack'
#depends 'rackops_rolebook'
#depends 'sudo'
#depends 'users'
